In [3]:
a= [[[1,2,3], 
     [2,3,4], 
     [3,4,5]]]
a

[[[1, 2, 3], [2, 3, 4], [3, 4, 5]]]

In [4]:
len(a)

1

In [7]:
import torch
position = torch.arange(0, 5, dtype=torch.float).unsqueeze(1)

In [6]:
print(position)

tensor([0., 1., 2., 3., 4.])


In [8]:
print(position)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])


In [9]:
pe = torch.zeros(5,4)
print(pe)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [10]:
pe[:, 0::2]

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])